# Import Data

In [2]:
import pandas as pd

# Load data yang sudah melewati tahap EDA dan Feature Engineering
DATA_PATH = '../data/'
df = pd.read_csv(DATA_PATH + 'processed_features.csv')

df.head()

C:\Users\blurtie\AppData\Local\Temp\ipykernel_15356\919128122.py:5: DtypeWarning: Columns (4,31) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(DATA_PATH + 'processed_features.csv')

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,...,q1_sec,q2_sec,q3_sec,best_qualy_sec,qualy_delta_sec,year,round,prior_points,prior_position,prior_wins
0,1,18,1,1,22,1.0,1,1,1,10.0,...,86.572,85.187,86.714,85.187,0.000,2008,1,0.0,20,0.0
1,2,18,2,2,3,5.0,2,2,2,8.0,...,85.960,85.518,87.236,85.518,0.331,2008,1,0.0,20,0.0
2,3,18,3,3,7,7.0,3,3,3,6.0,...,86.295,86.059,88.687,86.059,0.872,2008,1,0.0,20,0.0
3,4,18,4,4,5,11.0,4,4,4,5.0,...,86.907,86.188,NaN,86.188,1.001,2008,1,0.0,20,0.0
4,5,18,5,1,23,3.0,5,5,5,4.0,...,85.664,85.452,87.079,85.452,0.265,2008,1,0.0,20,0.0

In [3]:
# 1. Tentukan fitur prediktor (X) yang AMAN dan target (y)
# Kita tinggalkan semua kolom seperti 'points', 'laps', 'positionOrder', 'statusId', dll.
kolom_fitur = [
    'grid', 
    'qualy_delta_sec', 
    'prior_points', 
    'prior_position', 
    'prior_wins'
]

# Pastikan tidak ada data kosong yang tersisa di fitur-fitur penting ini
df_model = df.dropna(subset=kolom_fitur).copy()

# 2. Pemisahan Data Berdasarkan Waktu (Temporal Split)
# Misalnya: Kita jadikan musim 2023 ke atas sebagai data Uji (Testing), sisanya Pelatihan (Training)
tahun_batas_test = 2023

data_train = df_model[df_model['year'] < tahun_batas_test]
data_test = df_model[df_model['year'] >= tahun_batas_test]

# 3. Pisahkan X (Fitur) dan y (Target)
X_train = data_train[kolom_fitur]
y_train = data_train['is_podium']

X_test = data_test[kolom_fitur]
y_test = data_test['is_podium']

print(f"Jumlah Data Pelatihan (Sebelum {tahun_batas_test}): {len(X_train)} baris")
print(f"Jumlah Data Pengujian ({tahun_batas_test} - Sekarang): {len(X_test)} baris")

# 4. Cek struktur final dataset
X_train.head()

Jumlah Data Pelatihan (Sebelum 2023): 9428 baris
Jumlah Data Pengujian (2023 - Sekarang): 1536 baris

   grid  qualy_delta_sec  prior_points prior_position  prior_wins
0   1.0            0.000           0.0             20         0.0
1   5.0            0.331           0.0             20         0.0
2   7.0            0.872           0.0             20         0.0
3  11.0            1.001           0.0             20         0.0
4   3.0            0.265           0.0             20         0.0

# Model